config/routes.rb
Rails.application.routes.draw do
  #get 'parser/rushandball'
  devise_for :users
  resources :admin, only: [:index]
  scope '/admin' do
    resources :teams, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :leagues, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :seasons, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :tags, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :post_types, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :matches, shallow: true
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/admin', to: 'admin#index', as: 'user_root'
  get '/', to: 'application/index#index', as: 'index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/league.rb
class League < ApplicationRecord
    has_many :matches, dependent: :destroy
    validates :title, presence: true
    validates_uniqueness_of :title, :id
end 

app/models/match.rb
class Match< ApplicationRecord
    belongs_to :league
    belongs_to :season
    belongs_to :post_type
    has_and_belongs_to_many :teams, dependent: :destroy
    has_and_belongs_to_many :tags, dependent: :destroy
    validates :title, :datatime, :season_id, :league_id, :team_ids, :gender, :url, :post_type_id, presence: true
end   

app/models/post_type.rb
class PostType < ApplicationRecord
    has_many :matches
    validates :title, presence: true
    validates_uniqueness_of :title
end   

app/models/season.rb
class Season < ApplicationRecord
    has_many :matches, dependent: :destroy
    validates :title, presence: true
    validates_uniqueness_of :title, :id
end  

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :matches, dependent: :destroy
    validates :title, :description, presence: true
    validates_uniqueness_of :title
end   

app/models/team.rb
class Team < ApplicationRecord
    has_and_belongs_to_many :matches, dependent: :destroy
    validates :title, presence: true
    validates_uniqueness_of :title, :id
end  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :matches
  validates :fio, presence: true
end   

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"
  before_action :access
  
  def index
    @matches = Match.order(id: :desc).first(5)
    @teams = Team.order(id: :desc).first(5)
    @tags = Tag.order(id: :desc).first(5)
    @post_types = PostType.order(id: :desc).first(5)
    @leagues = League.order(id: :desc).first(5)
    @seasons = Season.order(id: :desc).first(5)
    @weeks = Match.
        joins(:league, :season, :post_type, :tags, :teams).
        where("datatime >= NOW() AND datatime <= NOW() + INTERVAL 7 DAY").order(:datatime).uniq
    @previous = Match.
        joins(:league, :season, :post_type, :tags, :teams).
        where("datatime <= NOW() AND datatime >= NOW() - INTERVAL 7 DAY").order(:datatime).uniq
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  layout "admin"
  before_action :access

  def index
    @leagues = League.all.order(:title)
  end

  def new
    @leagues = League.new
  end

  def edit
    @leagues = League.find(params[:id])
  end

  def create
    @leagues = League.new(league_params)

    if @leagues.save
      redirect_to leagues_path
    else
      render 'new'
    end
  end

  def update
    @leagues = League.find(params[:id])

    if @leagues.update(league_params)
      redirect_to leagues_path
    else
      render 'edit'
    end
  end

  def destroy
    @leagues = League.find(params[:id])
    @leagues.destroy

    redirect_to leagues_path
  end

  private
  def league_params
    params.require(:league).permit(:title)
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  layout "admin"
  before_action :access

  def index
    @seasons = Season.all.order(:title)
  end

  def new
    @season = Season.new
  end

  def edit
    @season = Season.find(params[:id])
  end

  def create
    @season = Season.new(season_params)

    if @season.save
      redirect_to seasons_path
    else
      render 'new'
    end
  end

  def update
    @season = Season.find(params[:id])

    if @season.update(season_params)
      redirect_to seasons_path
    else
      render 'edit'
    end
  end

  def destroy
    @season = Season.find(params[:id])
    @season.destroy

    redirect_to seasons_path
  end

  private
  def season_params
    params.require(:season).permit(:title)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  layout "admin"
  before_action :access

  def index
    @tags = Tag.all.order(:title)
  end

  def new
    @tags = Tag.new
  end

  def edit
    @tags = Tag.find(params[:id])
  end

  def create
    @tags = Tag.new(tag_params)

    if @tags.save
      redirect_to tags_path
    else
      render 'new'
    end
  end

  def update
    @tags = Tag.find(params[:id])

    if @tags.update(tag_params)
      redirect_to tags_path
    else
      render 'edit'
    end
  end

  def destroy
    @tags = Tag.find(params[:id])
    @tags.destroy

    redirect_to tags_path
  end

  private
  def tag_params
    params.require(:tag).permit(:title, :description)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  layout "admin"
  before_action :access

  def index
    @teams = Team.all.order(:title)
  end

  def new
    @team = Team.new
  end

  def edit
    @team = Team.find(params[:id])
  end

  def create
    @team = Team.new(team_params)

    if @team.save
      redirect_to teams_path
    else
      render 'new'
    end
  end

  def update
    @team = Team.find(params[:id])

    if @team.update(team_params)
      redirect_to teams_path
    else
      render 'edit'
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    redirect_to teams_path
  end

  private
  def team_params
    params.require(:team).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "admin"
  before_action :access

  def index
    @users = User.all.order(:id)
  end

  def edit
    @users = User.find(params[:id])
  end

  def update
    @users = User.find(params[:id])

    if @users.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def destroy
    @users = User.find(params[:id])
    @users.destroy

    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:fio, :email, :is_admin)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/post_types_helper.rb
module PostTypesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/seasons/_form.html.erb
<%= form_with model: @season, class: "text-center border border-light p-5", local: true do |form| %>
  <h5>Наименование</h5>
  <%= form.text_field :title, class: 'form-control mb-4', placeholder: 'Наименование', id: 'team'%>
  <% if @season.errors[:title].any? %>
    <div id="error_explanation" class="text-left orange-text">
      <ul style="list-style-type: none; padding-left: 0">
        <% @season.errors.full_messages_for(:title).each do |msg| %>
          <li><small><%= msg %></small></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.submit 'Подтвердить', class: 'btn btn-info btn-block my-4' %>
<% end %>

<style>
  html, body {
    height: 100%;
    position: relative;
  }
  footer {
    position: absolute;
    width: 100%;
  }
</style>

app/views/seasons/edit.html.erb
<div class="container text-center">
  <div class="row">
    <%= link_to 'Назад', seasons_path, class: 'btn white-text btn-sm cyan btn-rounded' %>
  </div>
  <p class="h3 mb-4">Редактировать данные сезона</p>
  <%= render 'form' %>
</div>

app/views/seasons/index.html.erb
<div class="container">
  <h1>Список сезонов</h1>
  <%= link_to 'Добавить сезон', new_season_path, class: 'btn btn-sm btn-primary btn-rounded' %>
  <div class="md-form mt-0">
    <input class="form-control" id="listSearch" type="text" placeholder="Искать" aria-label="Search">
  </div>
  <ul class="list-group" id="myList">
    <% @seasons.each do |season| %>
    <li class="list-group-item">
      <div class="row">
        <div class="col-md-6">
          <%= season.title %>
        </div>
        <div class="col-md-6 text-right">
          <%= link_to 'Изменить', edit_season_path(season), class: 'btn btn-sm btn-warning btn-rounded' %>
          <%= link_to 'Удалить', season_path(season), class: 'btn btn-sm btn-danger btn-rounded',
                          method: :delete,
                          data: { confirm: 'Вы уверены, что хотите удалить данный сезон из списка?' } %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $("#listSearch").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#myList li").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });
  });
</script>

app/views/seasons/new.html.erb
<div class="container">
  <div class="row">
    <%= link_to 'Назад', seasons_path, class: 'btn white-text btn-sm cyan btn-rounded' %>
  </div>
  <p class="h3 mb-4">Добавить сезон</p>
  <%= render 'form' %>
</div>