config/routes.rb
Rails.application.routes.draw do
  #get 'parser/rushandball'
  devise_for :users
  resources :admin, only: [:index]
  scope '/admin' do
    resources :teams, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :leagues, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :seasons, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :tags, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :post_types, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :matches, shallow: true
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/admin', to: 'admin#index', as: 'user_root'
  get '/', to: 'application/index#index', as: 'index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/league.rb
class League < ApplicationRecord
    has_many :matches, dependent: :destroy
    validates :title, presence: true
    validates_uniqueness_of :title, :id
end 

app/models/match.rb
class Match< ApplicationRecord
    belongs_to :league
    belongs_to :season
    belongs_to :post_type
    has_and_belongs_to_many :teams, dependent: :destroy
    has_and_belongs_to_many :tags, dependent: :destroy
    validates :title, :datatime, :season_id, :league_id, :team_ids, :gender, :url, :post_type_id, presence: true
end   

app/models/post_type.rb
class PostType < ApplicationRecord
    has_many :matches
    validates :title, presence: true
    validates_uniqueness_of :title
end   

app/models/season.rb
class Season < ApplicationRecord
    has_many :matches, dependent: :destroy
    validates :title, presence: true
    validates_uniqueness_of :title, :id
end  

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :matches, dependent: :destroy
    validates :title, :description, presence: true
    validates_uniqueness_of :title
end   

app/models/team.rb
class Team < ApplicationRecord
    has_and_belongs_to_many :matches, dependent: :destroy
    validates :title, presence: true
    validates_uniqueness_of :title, :id
end  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :matches
  validates :fio, presence: true
end   

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"
  before_action :access
  
  def index
    @matches = Match.order(id: :desc).first(5)
    @teams = Team.order(id: :desc).first(5)
    @tags = Tag.order(id: :desc).first(5)
    @post_types = PostType.order(id: :desc).first(5)
    @leagues = League.order(id: :desc).first(5)
    @seasons = Season.order(id: :desc).first(5)
    @weeks = Match.
        joins(:league, :season, :post_type, :tags, :teams).
        where("datatime >= NOW() AND datatime <= NOW() + INTERVAL 7 DAY").order(:datatime).uniq
    @previous = Match.
        joins(:league, :season, :post_type, :tags, :teams).
        where("datatime <= NOW() AND datatime >= NOW() - INTERVAL 7 DAY").order(:datatime).uniq
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  layout "admin"
  before_action :access

  def index
    @leagues = League.all.order(:title)
  end

  def new
    @leagues = League.new
  end

  def edit
    @leagues = League.find(params[:id])
  end

  def create
    @leagues = League.new(league_params)

    if @leagues.save
      redirect_to leagues_path
    else
      render 'new'
    end
  end

  def update
    @leagues = League.find(params[:id])

    if @leagues.update(league_params)
      redirect_to leagues_path
    else
      render 'edit'
    end
  end

  def destroy
    @leagues = League.find(params[:id])
    @leagues.destroy

    redirect_to leagues_path
  end

  private
  def league_params
    params.require(:league).permit(:title)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  layout "admin"
  before_action :access

  def index
    @matches = Match.
        joins(:teams).
        order(:datatime).uniq
  end

  def show
    @matches = Match.joins(:league, :season, :post_type, :tags, :teams).find(params[:id])
  end

  def new
    @matches = Match.new
  end

  def edit
    @matches = Match.find(params[:id])
  end

  def create
    @matches = Match.new(match_params)

    if @matches.save
      redirect_to matches_path
    else
      render 'new'
    end
  end

  def update
    @matches = Match.find(params[:id])

    if @matches.update(match_params)
      redirect_to matches_path
    else
      render 'edit'
    end
  end

  def destroy
    @matches = Match.find(params[:id])
    @matches.destroy

    redirect_to matches_path
  end

  private
  def match_params
    params.require(:match).permit(:title, :datatime, :description, :gender, :tour, :competition, :url, :league_id, :season_id, :post_type_id, team_ids:[], tag_ids:[])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  layout "admin"
  before_action :access

  def index
    @tags = Tag.all.order(:title)
  end

  def new
    @tags = Tag.new
  end

  def edit
    @tags = Tag.find(params[:id])
  end

  def create
    @tags = Tag.new(tag_params)

    if @tags.save
      redirect_to tags_path
    else
      render 'new'
    end
  end

  def update
    @tags = Tag.find(params[:id])

    if @tags.update(tag_params)
      redirect_to tags_path
    else
      render 'edit'
    end
  end

  def destroy
    @tags = Tag.find(params[:id])
    @tags.destroy

    redirect_to tags_path
  end

  private
  def tag_params
    params.require(:tag).permit(:title, :description)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  layout "admin"
  before_action :access

  def index
    @teams = Team.all.order(:title)
  end

  def new
    @team = Team.new
  end

  def edit
    @team = Team.find(params[:id])
  end

  def create
    @team = Team.new(team_params)

    if @team.save
      redirect_to teams_path
    else
      render 'new'
    end
  end

  def update
    @team = Team.find(params[:id])

    if @team.update(team_params)
      redirect_to teams_path
    else
      render 'edit'
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    redirect_to teams_path
  end

  private
  def team_params
    params.require(:team).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "admin"
  before_action :access

  def index
    @users = User.all.order(:id)
  end

  def edit
    @users = User.find(params[:id])
  end

  def update
    @users = User.find(params[:id])

    if @users.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def destroy
    @users = User.find(params[:id])
    @users.destroy

    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:fio, :email, :is_admin)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/post_types_helper.rb
module PostTypesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/leagues/_form.html.erb
<%= form_with model: @leagues, class: "text-center border border-light p-5", local: true do |form| %>
  <h5>Наименование</h5>
  <%= form.text_field :title, class: 'form-control mb-4', placeholder: 'Наименование', id: 'league'%>
  <% if @leagues.errors[:title].any? %>
    <div id="error_explanation" class="text-left orange-text">
      <ul style="list-style-type: none; padding-left: 0">
        <% @leagues.errors.full_messages_for(:title).each do |msg| %>
          <li><small><%= msg %></small></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.submit 'Подтвердить', class: 'btn btn-info btn-block my-4' %>
<% end %>

<style>
  html, body {
    height: 100%;
    position: relative;
  }
  footer {
    position: absolute;
    width: 100%;
  }
</style>

app/views/leagues/edit.html.erb
<div class="container text-center">
  <div class="row">
    <%= link_to 'Назад', leagues_path, class: 'btn white-text btn-sm cyan btn-rounded' %>
  </div>
  <p class="h3 mb-4">Редактировать данные лиги</p>
  <%= render 'form' %>
</div>

app/views/leagues/index.html.erb
<div class="container">
  <h1>Список лиг</h1>
  <%= link_to 'Добавить лигу', new_league_path, class: 'btn btn-sm btn-primary btn-rounded' %>
  <div class="md-form mt-0">
    <input class="form-control" id="listSearch" type="text" placeholder="Искать" aria-label="Search">
  </div>
  <ul class="list-group" id="myList">
    <% @leagues.each do |league| %>
    <li class="list-group-item">
      <div class="row">
        <div class="col-md-6">
          <%= league.title %>
        </div>
        <div class="col-md-6 text-right">
          <%= link_to 'Изменить', edit_league_path(league), class: 'btn btn-sm btn-warning btn-rounded' %>
          <%= link_to 'Удалить', league_path(league), class: 'btn btn-sm btn-danger btn-rounded',
                          method: :delete,
                          data: { confirm: 'Вы уверены, что хотите удалить данную лигу из списка?' } %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $("#listSearch").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#myList li").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });
  });
</script>

app/views/leagues/new.html.erb
<div class="container">
  <div class="row">
    <%= link_to 'Назад', leagues_path, class: 'btn white-text btn-sm cyan btn-rounded' %>
  </div>
  <p class="h3 mb-4">Добавить лигу</p>
  <%= render 'form' %>
</div>

app/views/matches/_form.html.erb
<%= form_with model: @matches, class: "border border-light p-5 row col-md-12", local: true do |form| %>
  <div class="col-md-12">
    <h3>Информация о матче</h3>
  </div>
  <div class="col-md-6">
    <h5>Название матча<span class="red-text" title="Обязательно для заполнения">*</span></h5>
    <%= form.text_field :title, class: 'form-control mb-4', placeholder: 'Наименование', id: 'team'%>
    <% if @matches.errors[:title].any? %>
      <div id="error_explanation" class="text-left orange-text">
        <ul style="list-style-type: none; padding-left: 0">
          <% @matches.errors.full_messages_for(:title).each do |msg| %>
            <li><small><%= msg %></small></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="col-md-6">
    <h5>Дата проведения<span class="red-text" title="Обязательно для заполнения">*</span></h5>
    <%= form.datetime_local_field :datatime, class: 'form-control mb-4', placeholder: 'Дата и время'%>
    <% if @matches.errors[:datatime].any? %>
      <div id="error_explanation" class="text-left orange-text">
        <ul style="list-style-type: none; padding-left: 0">
          <% @matches.errors.full_messages_for(:datatime).each do |msg| %>
            <li><small><%= msg %></small></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="col-md-12">
    <h5>Описание матча</h5>
    <%= form.text_area :description, class: 'form-control mb-4', placeholder: 'Описание'%>
  </div>
  <div class="col-md-3">
    <h5>Сезон<span class="red-text" title="Обязательно для заполнения">*</span></h5>
    <%= form.collection_select(:season_id, Season.all, :id, :title, { prompt: "Выберите сезон" }, { :class => "form-control mb-4 browser-default custom-select" })%>
    <% if @matches.errors[:season_id].any? %>
      <div id="error_explanation" class="text-left orange-text">
        <ul style="list-style-type: none; padding-left: 0">
          <% @matches.errors.full_messages_for(:season_id).each do |msg| %>
            <li><small><%= msg %></small></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <h5>Лига<span class="red-text" title="Обязательно для заполнения">*</span></h5>
    <%= form.collection_select(:league_id, League.all, :id, :title, { prompt: "Выберите лигу" }, { :class => "form-control mb-4 browser-default custom-select" })%>
    <% if @matches.errors[:league_id].any? %>
      <div id="error_explanation" class="text-left orange-text">
        <ul style="list-style-type: none; padding-left: 0">
          <% @matches.errors.full_messages_for(:league_id).each do |msg| %>
            <li><small><%= msg %></small></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <h5>Тур</h5>
    <%= form.select(:tour, [['Финал', 'Финал'], ['Preliminary Round', 'Preliminary Round'], ['Placement Matches', 'Placement Matches'], ['Main Group', 'Main Group'], ['Groups', 'Groups']], {prompt: "Выберите тур"}, {:class => "form-control mb-4 browser-default custom-select" }) %>
    <br>
  </div>
  <div class="col-md-3">
    <h5>Соревнование</h5>
    <%= form.text_field :competition, class: 'form-control mb-4', placeholder: 'Соревнование'%>
  </div>
  <div class="col-md-12">
    <h3 style="margin-top: 15px;">Команды матча</h3>
  </div>
  <div class="col-md-9">
    <h5>Команды<span class="red-text" title="Обязательно для заполнения">*</span></h5>
    <% if @matches.errors[:team_ids].any? %>
      <div id="error_explanation" class="text-left orange-text">
        <ul style="list-style-type: none; padding-left: 0">
          <% @matches.errors.full_messages_for(:team_ids).each do |msg| %>
            <li><small><%= msg %></small></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <div class="row" style="padding-left: 20px; padding-right: 20px;">
        <%= form.collection_check_boxes :team_ids, Team.all, :id, :title, { :max => 2 } do |b| %>
          <div class="collection-check-box" style="width: 170px">
            <%= b.check_box({:class => 'tms'}) %>
            <%= b.label %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <h5>Пол<span class="red-text" title="Обязательно для заполнения">*</span></h5>
    <%= form.select(:gender, [['Мужчины', 'Мужчины'], ['Женщины', 'Женщины'], ['Смешанный', 'Смешанный']], {prompt: "Выберите пол"}, {:class => "form-control mb-4 browser-default custom-select" }) %>
    <% if @matches.errors[:gender].any? %>
      <div id="error_explanation" class="text-left orange-text">
        <ul style="list-style-type: none; padding-left: 0">
          <% @matches.errors.full_messages_for(:gender).each do |msg| %>
            <li><small><%= msg %></small></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <br>
  </div>
  <div class="col-md-12">
    <h3 style="margin-top: 20px;">Видео</h3>
  </div>
  <div class="col-md-6">
    <h5>Ссылка на видео<span class="red-text" title="Обязательно для заполнения">*</span></h5>
    <%= form.text_field :url, class: 'form-control mb-4', placeholder: 'Ссылка на видео'%>
    <% if @matches.errors[:url].any? %>
      <div id="error_explanation" class="text-left orange-text">
        <ul style="list-style-type: none; padding-left: 0">
          <% @matches.errors.full_messages_for(:url).each do |msg| %>
            <li><small><%= msg %></small></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="col-md-6">
    <h5>Тип видео<span class="red-text" title="Обязательно для заполнения">*</span></h5>
    <%= form.collection_select(:post_type_id, PostType.all, :id, :title, { prompt: "Выберите тип поста" }, { :class => "form-control mb-4 browser-default custom-select" })%>
    <% if @matches.errors[:post_type_id].any? %>
      <div id="error_explanation" class="text-left orange-text">
        <ul style="list-style-type: none; padding-left: 0">
          <% @matches.errors.full_messages_for(:post_type_id).each do |msg| %>
            <li><small><%= msg %></small></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="col-md-12">
    <h3 style="margin-top: 15px;">Теги<span class="red-text" title="Обязательно для заполнения">*</span></h3>
    <% if @matches.errors[:tag_ids].any? %>
      <div id="error_explanation" class="text-left orange-text">
        <ul style="list-style-type: none; padding-left: 0">
          <% @matches.errors.full_messages_for(:tag_ids).each do |msg| %>
            <li><small><%= msg %></small></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <div class="row" style="padding-left: 20px; padding-right: 20px;">
        <%= form.collection_check_boxes :tag_ids, Tag.all, :id, :title, { :max => 2 } do |b| %>
          <div class="collection-check-box" style="width: 150px">
            <%= b.check_box({:class => 'tgs'})%>
            <%= b.label %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= form.submit 'Подтвердить', class: 'btn btn-info btn-block my-4' %>
<% end %>

<style>
  /*.form-control {*/
  /*  margin-bottom: 5px !important;*/
  /*}*/
    span {
      cursor: default;
    }
</style>

app/views/matches/edit.html.erb
<div class="container">
  <div class="row">
    <%= link_to 'Назад', matches_path, class: 'btn white-text btn-sm cyan btn-rounded' %>
  </div>
  <p class="h3 mb-4">Изменить данные матча</p>
  <%= render 'form' %>
</div>

app/views/matches/index.html.erb
<div class="container">
  <h1>Список матчей</h1>
  <%= link_to 'Добавить матч', new_match_path, class: 'btn btn-sm btn-primary btn-rounded' %>
  <div class="md-form mt-0">
    <input class="form-control" id="listSearch" type="text" placeholder="Искать" aria-label="Search">
  </div>
  <ul class="list-group" id="myList">
    <% @matches.each do |match| %>
    <li class="list-group-item">
      <div class="row">
        <div class="col-md-6">
          <div class="row col-md-12">
            <% match.teams.each_with_index { |team, i| %>
            <% if i == 0 %>
            <h5 style="margin-bottom: 0px"><%= team.title %>&nbsp;vs&nbsp;</h5>
            <% else %>
            <h5 style="margin-bottom: 0px"><%= team.title %></h5>
            <% end %>
            <% } %>
          </div>
          <small><%= match.datatime %></small> <br>
          <small><%= match.description %></small> <br>
        </div>
        <div class="col-md-6 text-right">
          <%= link_to 'Изменить', edit_match_path(match), class: 'btn btn-sm btn-warning btn-rounded' %>
          <%= link_to 'Удалить', match_path(match), class: 'btn btn-sm btn-danger btn-rounded',
                        method: :delete,
                        data: {confirm: 'Вы уверены, что хотите удалить матч?'} %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $("#listSearch").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#myList li").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });
  });
</script>

app/views/matches/new.html.erb
<div class="container">
  <div class="row">
    <%= link_to 'Назад', matches_path, class: 'btn white-text btn-sm cyan btn-rounded' %>
  </div>
  <p class="h3 mb-4">Добавить матч</p>
  <%= render 'form' %>
</div>

app/views/matches/show.html.erb
<div class="container">
  <div class="right">
    <%= link_to 'Назад', matches_path, class: 'btn btn-sm btn-info btn-rounded' %>
    <%= link_to 'Изменить', edit_match_path(params[:id]), class: 'btn btn-sm btn-warning btn-rounded' %>
  </div>
  <div class="row main">
    <div class="col-md-8">
      <p>Здесь будет плеер</p>
      <p><%= @matches.url %></p>
    </div>
    <div class="col-md-4">
      <div class="blue-grey" style="padding: 15px 15px 15px 15px">
        <small class="white-text"><%= @matches.datatime %></small>
        <div class="row" style="padding: 5px 15px 5px 15px">
          <% @matches.teams.each_with_index { |team, i| %>
          <% if i == 0 %>
          <h5 class="white-text" style="margin-bottom: 0px"><%= team.title %>&nbsp;vs&nbsp;</h5>
          <% else %>
          <h5 class="white-text" style="margin-bottom: 0px"><%= team.title %></h5>
          <% end %>
          <% } %>
        </div>
        <p class="white-text" style="margin-bottom: 10px; font-size: 12px"><%= @matches.description %></p>
        <% @matches.tags.each { |tag| %>
        <span class="badge badge-pill badge-primary">#<%= tag.title %></span>
        <% } %>
        <br>
        <div class="row" style="padding: 10px 15px 5px 15px">
          <small class="white-text"><%= @matches.post_type.title %></small>
        </div>
      </div>
      <div>
        <table class="table table-striped">
          <tbody>
            <tr>
              <td>Лига</td>
              <td class="text-right"><%= @matches.league.title %></td>
            </tr>
            <tr>
              <td>Соревнование</td>
              <td class="text-right"><%= @matches.competition %></td>
            </tr>
            <tr>
              <td>Сезон</td>
              <td class="text-right"><%= @matches.season.title %></td>
            </tr>
            <tr>
              <td>Тур</td>
              <td class="text-right"><%= @matches.tour %></td>
            </tr>
            <tr>
              <td>Тип команды</td>
              <td class="text-right"><%= @matches.gender %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<style>
  span {
    cursor: pointer;
  }

  .main {
    margin-bottom: 13px;
  }

  small,
  p,
  h5 {
    cursor: default;
  }
</style>

app/views/tags/_form.html.erb
<%= form_with model: @tags, class: "text-center border border-light p-5", local: true do |form| %>
  <h5>Наименование</h5>
  <%= form.text_field :title, class: 'form-control mb-4', placeholder: 'Наименование', id: 'team'%>
  <% if @tags.errors[:title].any? %>
    <div id="error_explanation" class="text-left orange-text">
      <ul style="list-style-type: none; padding-left: 0">
        <% @tags.errors.full_messages_for(:title).each do |msg| %>
          <li><small><%= msg %></small></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h5>Описание</h5>
  <%= form.text_area :description, class: 'form-control mb-4', placeholder: 'Краткое описание', id: 'desc'%>
  <% if @tags.errors[:description].any? %>
    <div id="error_explanation" class="text-left orange-text">
      <ul style="list-style-type: none; padding-left: 0">
        <% @tags.errors.full_messages_for(:description).each do |msg| %>
          <li><small><%= msg %></small></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.submit 'Подтвердить', class: 'btn btn-info btn-block my-4' %>
<% end %>

<style>
  html, body {
    height: 100%;
    position: relative;
  }
  footer {
    position: absolute;
    width: 100%;
  }
</style>

app/views/tags/edit.html.erb
<div class="container text-center">
  <div class="row">
    <%= link_to 'Назад', tags_path, class: 'btn white-text btn-sm cyan btn-rounded' %>
  </div>
  <p class="h3 mb-4">Редактировать данные тега</p>
  <%= render 'form' %>
</div>

app/views/tags/index.html.erb
<div class="container">
  <h1>Список команд</h1>
  <%= link_to 'Добавить тег', new_tag_path, class: 'btn btn-sm btn-primary btn-rounded' %>
  <div class="md-form mt-0">
    <input class="form-control" id="listSearch" type="text" placeholder="Искать" aria-label="Search">
  </div>
  <ul class="list-group" id="myList">
    <% @tags.each do |tag| %>
    <li class="list-group-item">
      <div class="row">
        <div class="col-md-6">
          <%= tag.title %> <br>
          <small><%= tag.description %></small>
        </div>
        <div class="col-md-6 text-right">
          <%= link_to 'Изменить', edit_tag_path(tag), class: 'btn btn-sm btn-warning btn-rounded' %>
          <%= link_to 'Удалить', tag_path(tag), class: 'btn btn-sm btn-danger btn-rounded',
                          method: :delete,
                          data: { confirm: 'Вы уверены, что хотите удалить данный тег из списка?' } %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $("#listSearch").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#myList li").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });
  });
</script>

app/views/tags/new.html.erb
<div class="container">
  <div class="row">
    <%= link_to 'Назад', tags_path, class: 'btn white-text btn-sm cyan btn-rounded' %>
  </div>
  <p class="h3 mb-4">Добавить тег</p>
  <%= render 'form' %>
</div>

app/views/users/_form.html.erb
<%= form_with model: @users, class: "border border-light p-5", local: true do |form| %>
  <h5>Доступ к панели администратора</h5>
  <%= @users.fio %>&nbsp;(<%= @users.email %>) <br>
    <%= form.radio_button :is_admin, 0 %> Запретить <br>
    <%= form.radio_button :is_admin, 1 %> Разрешить
  <% if @users.errors[:is_admin].any? %>
    <div id="error_explanation" class="text-left orange-text">
      <ul style="list-style-type: none; padding-left: 0">
        <% @users.errors.full_messages_for(:title).each do |msg| %>
          <li><small><%= msg %></small></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.submit 'Подтвердить', class: 'btn btn-info btn-block my-4' %>
<% end %>

<style>
  html, body {
    height: 100%;
    position: relative;
  }
  footer {
    position: absolute;
    width: 100%;
  }
</style>

app/views/users/edit.html.erb
<div class="container text-center">
  <div class="row">
    <%= link_to 'Назад', users_path, class: 'btn white-text btn-sm cyan btn-rounded' %>
  </div>
  <p class="h3 mb-4">Редактировать данные пользователя</p>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1>Список пользователей</h1>
  <div class="md-form mt-0">
    <input class="form-control" id="listSearch" type="text" placeholder="Искать" aria-label="Search">
  </div>
  <ul class="list-group" id="myList">
    <% @users.each do |user| %>
    <li class="list-group-item">
      <div class="row">
        <div class="col-md-6">
          <%= user.fio %> <br>
          <small><%= user.email %></small> <br>
          <% if user.is_admin? %>
          <small>Доступ разрешен</small>
          <% else %>
          <small>Доступ запрещен</small>
          <% end %>
        </div>
        <div class="col-md-6 text-right">
          <%= link_to 'Изменить', edit_user_path(user), class: 'btn btn-sm btn-warning btn-rounded' %>
          <%= link_to 'Удалить', user_path(user), class: 'btn btn-sm btn-danger btn-rounded',
                          method: :delete,
                          data: { confirm: 'Вы уверены, что хотите удалить пользователя из списка?' } %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $("#listSearch").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#myList li").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });
  });
</script>